version: '3.4'

volumes:
  postgres_data:
    driver: local

x-variables: &database
    POSTGRES_DB: ****
    POSTGRES_USER: ****
    POSTGRES_PASSWORD: ****

services:

### Reverse proxy

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/live/mojeakwarele.pl/cert.pem:/etc/ssl/private/cert.pem
      - /etc/letsencrypt/live/mojeakwarele.pl/chain.pem:/etc/ssl/private/chain.pem
      - /etc/letsencrypt/live/mojeakwarele.pl/fullchain.pem:/etc/ssl/private/fullchain.pem
      - /etc/letsencrypt/live/mojeakwarele.pl/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - catalogue

  buildpage:
    image: watercolors_buildpage
    container_name: buildpage
    ports:
      - 80

### Main services

  catalogue:
    image: watercolors_catalogue
    hostname: catalogue
    container_name: catalogue
    environment:
      <<: *database
      DB_SERVER: postgres
      SERVER: https://api.mojeakwarele.pl
    volumes: 
      - ~/watercolors:/root/watercolors
    ports:
      - 8080
    depends_on:
      - postgres 

  mail:
    image: watercolors_mail
    container_name: mail
    environment:
      <<: *database
      DB_SERVER: postgres
      SERVER: https://api.mojeakwarele.pl
      NEWSLETTER_WELCOME_SUBJECT: Witaj w newsletterze Moje Akwarele
      WELCOME_TEMPLATE: welcome
    volumes: 
      - ~/watercolors:/root/watercolors
    ports:
      - 8090
    depends_on:
      - postgres

### Database

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      <<: *database